### ISSUE TITLE
Create journey map of agency users

### ISSUE THREAD

**Issue by porta-antiporta** [18F/disa-eagency#1]
From our kickoff, there were various journeys that agency users have that were not captured in the journey map.  We want to create these journey(s) so that we can evaluate where there are areas for simplification / streamlining. 

Some potential candidate journeys to map out:

- [ ] Initial agency configuration
- [ ] Initiation of an investigation
- [ ] Tracking the investigation

Note: there will be a separate story to optimize/simplify the journey

**Comment by lauraponce** [comment]
Updated version of the journey map that reflects additions and changes from the kickoff:
 [eAgencyJourneyMap.pdf](https://github.com/18F/disa-eagency/files/1411159/eAgencyJourneyMap.pdf)

I'm working on a +/- version of the journey map now that shows where the pain points are

**Comment by porta-antiporta** [comment]
Is that an export of a MURAL?  If so, could we get a link to the MURAL?

**Comment by lauraponce** [comment]
@porta-antiporta it's a Sketch file, GitHub won't let me attach it here, so I added it to Slack

**Comment by lauraponce** [comment]
Second version that's more consolidated and incorporates pain points: 
[eQIPEmotionalJourney.pdf](https://github.com/18F/disa-eagency/files/1413217/eQIPEmotionalJourney.pdf)
