### ISSUE TITLE
Verify that GitHub is sending issue open, comment, close messages to Slack

### ISSUE THREAD

**Issue by yozlet** [18F/disa-eagency#10]

**Comment by yozlet** [comment]
![3d4633eb892cbb5bcfea782b65bafa6e--burritos-tacos](https://user-images.githubusercontent.com/173848/33393012-95c67b36-d4f2-11e7-969d-ab27f26c43bb.jpg)

**Comment by porta-antiporta** [comment]
YOOOOOOOOOOZZZZ!

**Comment by yozlet** [comment]
About bloody time
